/**
 * Load Test: War Engine Phase (300 concurrent students)
 * 
 * Target: 0 double claims, p95 < 300ms.
 * 
 * HOW TO RUN:
 * 1. Start the local Docker Compose environment:
 *    docker compose up -d
 * 2. Set the JWT_SECRET locally (must match your app's secret or default 'dev-secret')
 *    export JWT_SECRET=dev-secret
 * 3. Run the seed script to generate test data and JWTs:
 *    npx tsx test/load/seed.ts
 * 4. Run the k6 script:
 *    k6 run test/load/war-engine.js
 */

import http from 'k6/http';
import { check, sleep } from 'k6';
import { SharedArray } from 'k6/data';

// Load data generated by the seed script
const data = new SharedArray('Load test data', function () {
  return [JSON.parse(open('./data.json'))];
});

export const options = {
  scenarios: {
    war: {
      executor: 'per-vu-iterations',
      vus: 300,
      iterations: 1,
      maxDuration: '30s',
    },
  },
};

export default function () {
  const d = data[0];
  const vuIdx = __VU - 1; // 0 to 299
  
  // Guard against undefined users (just in case)
  if (!d.users[vuIdx]) {
    return;
  }
  
  const user = d.users[vuIdx];
  const url = `http://localhost:3000/api/war/claims`;
  
  // Each student tries to pick a random thesis from the list to simulate high contention
  // We'll target the same 10 thesis IDs to ensure collisions occur
  const targetThesisId = d.thesisIds[vuIdx % 10]; 
  
  const payload = JSON.stringify({
    periodId: user.periodId,
    thesisId: targetThesisId,
    priority: 1
  });

  const params = {
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${user.token}`
    },
  };

  // Sleep a random amount (0-500ms) to simulate students clicking at slightly different times around opens_at
  sleep(Math.random() * 0.5);

  const res = http.post(url, payload, params);

  // We expect either 201 (success) or 409 (already taken)
  check(res, {
    'status is 201 or 409': (r) => r.status === 201 || r.status === 409,
    'response time < 300ms': (r) => r.timings.duration < 300,
  });
}
